---
title: "HCP Wellbeing Survey"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    #vertical_layout: fill
---

```{r setup, include=FALSE}
.libPaths("C:/Users/alessandra.bisquera/AppData/Local/R/win-library/4.2")
library(flexdashboard)
library(tidyverse)
library(plotly)
library(leaflet)
library(kableExtra)
```

Demographics
=====================================  

Row {data-height=350}
-----------------------------------------------------------------------

### Number of respondents  {.value-box}
```{r}
nresp <- 150
valueBox(nresp, icon = "fa-comments")
```


### Number of countries  {.value-box}
```{r}
ncountr <- 15
valueBox(ncountr, icon = "fa-pencil")
```



Row
-----------------------------------------------------------------------

### Responses by location {data-width=650}

```{r }
# Create 20 markers (Random points)
data = data.frame(
   long=sample(seq(-150,150),20),
   lat=sample(seq(-50,50),20),
   val=round(rnorm(20, mean=100, sd=50),0)
   
) 
data$val <- abs(data$val)
data$name <- paste0("country_",letters[1:20],": ", data$val)
 
# Show a circle at each position
m=leaflet(data = data) %>%
   addTiles() %>%
   addCircleMarkers(
      ~long, ~lat, 
      radius=~val*0.2 , 
      color=~ifelse(data$val>100 , "red", "orange"),
      stroke = TRUE, 
      fillOpacity = 0.2,
      popup = ~as.character(name),
    label = ~val,
    labelOptions = labelOptions(noHide = TRUE,textOnly = TRUE,
                                direction = "center",
                                style = list(
                                  "color" = "black", 
                                  "font-weight" = "bold",
                                  "font-size" = "15px"
                                )))
m



```

Row
-----------------------------------------------------------------------
### Age  {data-height=350}

```{r}
# 
slices <- c(10, 12, 4, 16, 8)

lbls <- c("30-39", "40-49", "50-59", "60-69", "70+")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct)
# add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels
pie(slices,labels = lbls, col=rainbow(length(lbls)),
   main="Age of respondents")

```

### Professional status  {data-height=350}

```{r}

df <- data.frame(dose=c("Retinal specialist", "Resident Doctor", "General Opthalmologist"),
                len=c(4, 10, 30))

p<-ggplot(df, aes(x=dose, y=len, fill=dose)) +
  geom_bar(stat="identity")+theme_minimal() +
  labs(x="", y="N") +
  theme(legend.position="none",axis.text=element_text(size=12))
  
p

```



Clinic capacity 
===================================== 

Row
-------------------------------------

### Clinic capacity {data-width=700}

```{r}

df2 <- data.frame(x=c("Yes", "No"), y=c(20, 30))

p<-ggplot(df2, aes(x=x, y=y, fill=x)) +
  geom_bar(stat="identity")+theme_minimal() +
  labs(x="", y="N", title="Do you feel that capacity is an issue in your clinic?") +
  theme(legend.position="none",axis.text=element_text(size=16),
        plot.title = element_text(size=15))
  
p

```

### Impact {data-width=340}

```{r}


df3 <- data.frame(Answer=c("Less time to socialize", "Struggle to maintain \na healthy work life balance",
                      "I feel a constant \nsense of being rushed"), N=c(10, 30,50))

df3 %>% 
kbl(caption = "How are you personally impacted by clinic capacity constraints?" ) %>%
  kable_paper(bootstrap_options = "striped", full_width = F, position = "left")

```   


